x-setup: &setup
  image: cpp-dev
  build:
    context: ..
    dockerfile: ./.devcontainer/Dockerfile_debian_clang-19
  stdin_open: true
  tty: true
  network_mode: host
  environment:
    SSH_AUTH_SOCK: /ssh-agent
  ulimits:
    nofile:
      soft: 1024
      hard: 1024

x-volume-cppproject: &volume-cppproject
  type: bind
  source: ../
  target: /home/build/cppproject

x-volume-conan2-cache: &volume-conan2-cache
  type: bind
  source: ./conan2_cache
  target: /home/build/.conan2

services:
  cppproject:
    <<: *setup
    volumes:
      - <<: *volume-cppproject
      - <<: *volume-conan2-cache
      - type: bind
        source: ${SSH_AUTH_SOCK:-/dev/null}
        target: /ssh-agent
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri