version: "3.9"

x-setup: &setup
  image: cpp-dev
  build:
    context: ..
    dockerfile: ./.devcontainer/Dockerfile_clang-19
  stdin_open: true
  tty: true
  network_mode: host
  environment:
    SSH_AUTH_SOCK: /ssh-agent

x-volume-cppproject: &volume-cppproject
  type: bind
  source: ../
  target: /home/build/cppproject

services:
  cppproject:
    <<: *setup
    volumes:
      - <<: *volume-cppproject
      - type: bind
        source: ${SSH_AUTH_SOCK:-/dev/null}
        target: /ssh-agent
